### ISSUE TITLE
add liveness, readiness and resources in k8s examples

### ISSUE THREAD

**Issue by JorritSalverda** [GoogleCloudPlatform/endpoints-samples#24]
For the b.gcr.io/endpoints/endpoints-runtime:0.3 container is there an endpoint to test for liveness and/or readiness?

And what resources does it need?

**Comment by kyessenov** [comment]
For readiness and, perhaps, liveness probe, you can use "/endpoints_status" on the status port, which is 8090 by default:
```
  readinessProbe:
        httpGet:
          path: /endpoints_status
          port: 8090
```
Note that /endpoints_status triggers some minimal stats collection, so it's probably better to define another endpoint that just returns 200. We added one by default recently, but it's not released yet.
If you have a custom nginx config, you can also add another location manually.
